apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01 
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /mnt/spark/storage
    server: 10.100.31.96 
  persistentVolumeReclaimPolicy: Retain 
